### ISSUE TITLE
Convert GitHub URLs into clickable hyperlinks

### ISSUE THREAD

**Issue by hisplan** [foryourjoy/bcd-team-project#4]
To enhance the usability of a URL, please convert GitHub URLs into clickable hyperlinks. This allows users to navigate directly to the repository by simply clicking on the link, rather than having to copy and paste the URL into their browser.

This must be done by each member of your team.

@foryourjoy @JeonJeong-eun @bangeunju @jamesksh0130

**Comment by foryourjoy** [comment]
Each team members changed Github URLs into clickable hyperlinks. 
Thanks for your information!
